package com.dom.project.enum_;

/**
 * 操作ログ種別列挙。
 */
public enum OperationTypeEnum {

    LOGIN("LOGIN"),
    DORMITORY_CREATE("DORMITORY_CREATE"),
    DORMITORY_UPDATE("DORMITORY_UPDATE"),
    DORMITORY_DELETE("DORMITORY_DELETE"),
    AFFILIATION_CREATE("AFFILIATION_CREATE"),
    AFFILIATION_UPDATE("AFFILIATION_UPDATE"),
    AFFILIATION_DELETE("AFFILIATION_DELETE"),
    REGION_CREATE("REGION_CREATE"),
    REGION_UPDATE("REGION_UPDATE"),
    REGION_DELETE("REGION_DELETE"),
    USAGE_TYPE_CREATE("USAGE_TYPE_CREATE"),
    USAGE_TYPE_UPDATE("USAGE_TYPE_UPDATE"),
    USAGE_TYPE_DELETE("USAGE_TYPE_DELETE"),
    UNIT_PRICE_CREATE("UNIT_PRICE_CREATE"),
    UNIT_PRICE_UPDATE("UNIT_PRICE_UPDATE"),
    UNIT_PRICE_DELETE("UNIT_PRICE_DELETE"),
    EMPLOYEE_CREATE("EMPLOYEE_CREATE"),
    EMPLOYEE_UPDATE("EMPLOYEE_UPDATE"),
    EMPLOYEE_DELETE("EMPLOYEE_DELETE"),
    ROOM_CREATE("ROOM_CREATE"),
    ROOM_UPDATE("ROOM_UPDATE"),
    ROOM_DELETE("ROOM_DELETE"),
    RESIDENCE_CREATE("RESIDENCE_CREATE"),
    RESIDENCE_CHECKOUT("RESIDENCE_CHECKOUT"),
    DORM_FEE_CREATE("DORM_FEE_CREATE"),
    DORM_FEE_CONFIRM("DORM_FEE_CONFIRM"),
    EQUIPMENT_CREATE("EQUIPMENT_CREATE"),
    EQUIPMENT_UPDATE("EQUIPMENT_UPDATE"),
    EQUIPMENT_DELETE("EQUIPMENT_DELETE"),
    EQUIPMENT_MOVEOUT("EQUIPMENT_MOVEOUT"),
    EQUIPMENT_STORAGE_CREATE("EQUIPMENT_STORAGE_CREATE"),
    EQUIPMENT_ASSET_CREATE("EQUIPMENT_ASSET_CREATE"),
    EQUIPMENT_ASSET_UPDATE("EQUIPMENT_ASSET_UPDATE"),
    EQUIPMENT_ASSET_DELETE("EQUIPMENT_ASSET_DELETE"),
    DORMITORY_MANAGER_ASSIGN("DORMITORY_MANAGER_ASSIGN"),
    DORMITORY_MANAGER_REMOVE("DORMITORY_MANAGER_REMOVE"),
    EXCEL_IMPORT_EXECUTE("EXCEL_IMPORT_EXECUTE");

    private final String code;

    OperationTypeEnum(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
